spring:
  profiles:
    active: prod
  application:
    name: hello-service

management:
      endpoints:
        web:
          exposure:
            include: "*"
server:
  port: 8880

book:
  name: SpringCloud-c1
  author: Ben-develop-c1
  desc: ${book.author} is writing ${book.name}

