spring:
  application:
    name: hello-service

management:
      endpoints:
        web:
          exposure:
            include: "*"
server:
  port: 8880

book:
  name: SpringCloud-master
  author: Ben-master-c1
  desc: ${book.author} is writing ${book.name}

