spring:
  profiles:
    active: prod
  application:
    name: hello-service

management:
      endpoints:
        web:
          exposure:
            include: "*"
server:
  port: 8880

book:
  name: SpringCloudMaster
  author: Ben
  desc: ${book.author} is writing ${book.name}

